//Object.assign method: Object.assign({}, ['a','b','c']); // {0:"a", 1:"b", 2:"c"}
//array to json: https://stackoverflow.com/questions/2295496/convert-array-to-json


//create simple model schema and import into the collection db one property
//import: modify into a json file and use the mongo import command
//restaurants json file lesson???

const motvQuotes = [
	"Wow, I really regret that workout. – No One. Ever.",
	'When nothing goes right… go lift.',
	'The only one who can tell you “you can’t” is you, and you don’t have to listen.',  
	'There are choices and then there are excuses. Not both.',
	'Running is nothing more than a series of arguments between the part of your brain that wants to stop and the part that wants to keep going.',
	'Better sore than sorry.',
	'A change may be just around the corner.',
	"One of the greatest moments in life is realizing that two weeks ago, your body couldn't do that.",
	"Shut up. Work hard. Be patient.",  
	"Remember that guy that gave up? Neither does anybody else.",  
	"Today I will do what others won’t, so tomorrow I can accomplish what others can’t.",
	"Do something today that your future self will thank you for.",
	"We are what we repeatedly do. Excellence then is not an act but a habit.",
	"No matter how slow you go, you are still lapping everybody on the couch.",
	"You miss 100% of the shots you don’t take.",
	"The difference between the impossible and the possible lies in a person’s determination.",
	"If you want something you’ve never had, you must be willing to do something you’ve never done.",
	"To give anything less than your best is to sacrifice the gift.",
	"You’re only one workout away from a good mood.",
	"Nothing will work unless you do.",
	"Life begins at the end of your comfort zone.",
	"Strength does not come from physical capacity. It comes from an indomitable will.",
	"The difference between try and triumph is a little ‘umph’.",
	"Don’t count the days, make the days count.",
	"Making excuses burns zero calories per hour.",
	"If you’re tired of starting over, stop giving up.",
	"When you feel like quitting, think about why you started.",
	"Do what you have to do until you can do what you want to do.",
	"Create healthy habits, not restrictions.",
	"Don’t let the scale define you. Be active, be healthy, be happy.",
	"It’s going to be a journey. It’s not a sprint to get fit.",
	"No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn’t trying.",
	"Just believe in yourself. Even if you don’t pretend that you do and, and some point, you will.",
	"Strive for progress, not perfection.",
	"All great achievements require time.",
	"We cannot start over. But we can begin now and make a new ending.",
	"Every day is another chance to get stronger, to eat better, to live healthier, and to be the best version of you.",
	"Wake up. Work out. Kick ass. Repeat.",
	"The hardest lift of all is lifting your butt off the couch.",
	"Sore. The most satisfying pain.",
	"The best way to predict the future is to create it.",
	"The difference between your body this week and next week is what you do for the next seven days to achieve your goals.",
	"If you change the way you look at things, the things you look at change.",
	"I will make sweat my best accessory. I will run harder than my mascara.",
	"Fit is not a destination, it is a way of life.",
	"Making excuses burns zero calories per hour.",
	"Stay positive. Work hard. Make it happen.",
	"YOGA because punching people is frowned upon.",
	"If you're not sweating, you're not working.",
	"You may not be there yet. But you're closer than yesterday.",
	"You don't get the ass you want sitting on it.",
	"Sweat is just fat crying.",
	"Sweat is magic. Cover yourself with it daily to grant your wishes.",
	"Learn to love the burn.",
	"Sweat. Smile. Repeat.",
	"You vs. You. Be your own motivation.",
	"Don't wish for a good body. Work for it.",
	"Work harder. Eat better. Run faster. Feel stronger.",
	"Change nothing and nothing changes.",
	"Stop dreaming. Start doing.",
	"Set the bar and conquer.",
	"Exercise equals endorphins. Endorphins make you :-D", 
	"Your legs are not giving out. Your head is giving up. Keep going.", 
	"Your desire to change must be greater than your desire to stay the same.",    
	"You’ve only got 3 choices in life: Give up, give in, or give it all you’ve got.",  
	"You’re only one workout away from a good mood.", 
	"You will never know your limits unless you push yourself to them.",  
	"You only regret the workouts you don’t do.", 
	"You have to expect things of yourself before you can do them.",  
	"You have a choice. You can throw in the towel, or you can use it to wipe the sweat off your face.",  
	"You don’t have to be great to start, but you have to start to be great.",  
	"You can’t start the next chapter of your life if you keep rereading the last one.",  
	"You can feel sore tomorrow or you can feel sorry tomorrow. You choose.",  
	"You are a perishable item. Live accordingly.",  
	"Whether you think you can, or you think you can’t – you’re right.", 
	"What would you attempt to do if you knew you could not fail?",
	"What did you do today to bring you one step closer to your goal?",  
	"We cannot become what we want to be by remaining what we are.", 
	"Transformation is not a future event. It is a present activity.",  
	"Today I will do what others won’t, so tomorrow I can do what others can’t.",  
	"Those who think they have no time for healthy eating will sooner or later have to find time for illness.",  
	"There’s no such thing as bad weather. Just soft people.",   
	"There are no shortcuts to any place worth going.",  
	"The timing rarely seems “right” until we’re looking back. Stop making excuses for your dreams.",  
	"The only way to define your limits is by going beyond them.",  
	"The only disability in life is a bad attitude.",  
	"The miracle isn’t that I finished. The miracle is that I had the courage to start.",  
	"The greatest pleasure in life is doing what people say you cannot do.",  
	"The good stuff is always worth the work it takes.",  
	"The first step towards getting somewhere is to decide that you are not going to stay where you are.",  
	"The difference between who you are and who you want to be is what you do.",  
	"The body achieves what the mind believes.",  
	"That voice inside your head that’s saying you can’t do it is a liar.",  
	"Take care of your body. It’s the only place you have to live.",  
	"Surround yourself with people who believe in your dreams.",  
	"Success doesn’t happen overnight. Keep your eyes on the prize and don’t look back.",  
	"Strive for progress, not perfection.",
	"Stop waiting for things to happen. Go out and make them happen.", 
	"Start where you are. Use what you have. Do what you can.",  
	"Sore? Tired? Out of Breath? Good. It’s Working.",  
	"Small changes can make a big difference.",  
	"Running slow isn’t a character flaw. Quitting is.",  
	"Remind yourself frequently how far you’ve come.",  
	"Push yourself. Because no one else is going to do it for you.",
	"Overcome the notion that you must be regular. It robs you of the chance to be extraordinary.",  
	"One pound at a time.",
	"Note to self: When I eat like crap, I feel like crap.",  
	"No one can make you feel inferior without your permission.",  
	"Never give up on something you really want. It’s difficult to wait, but worse to regret.",  
	"Motivation is what gets you started. Habit is what keeps you going.",  
	"Limitations exist only if you let them.",  
	"Life has no remote. Get up and change it yourself.",  
	"Life begins at the end of your comfort zone.",  
	"Keep smiling and one day life will get tired of upsetting you.",  
	"Junk food you’ve craved for an hour, or the body you’ve craved for a lifetime? Your decision.",  
	"It’s not who you are that holds you back, it’s who you think you’re not.",  
	"It’s not about having time. It’s about making time.",  
	"It’s all about creating healthy habits rather than restrictions.",  
	"It took more than a day to put it on. It will take more than a day to take it off.",  
	"It doesn’t matter who’s faster or stronger than you. All that matters is YOU are better than the previous you.",  
	"It always seems impossible until it’s done.",  
	"Impossible isn’t a fact. It’s an opinion. Impossible isn’t a declaration. It’s a dare. Impossible is potential. Impossible is nothing.",  
	"If you’re tired of starting over, stop giving up.",  
	"If you wait for perfect conditions, you’ll never get anything done.",  
	"If you keep good food in your fridge, you will eat good food.",  
	"If you change nothing, nothing will change.",  
	"If it’s important to you, you will find a way. If not, you’ll find an excuse.",
	"I’m not telling you it’s going to be easy, I’m telling you it’s going to be worth it.",
	"I’m not giving up, I’m just starting over.",  
	"I would rather have a life of “oh wells” than a life of “what ifs”.",  
	"I want people to be blown away when I do what they don’t expect.", 
	"I do not run to add days to my life. I run to add life to my days.",  
	"Health is a relationship between you and your body.",  
	"Good, better, best. Never let it rest until your good is better, and your better is best.",  
	"Forget about getting skinny. Eat well and exercise. The weight will take care of itself.",  
	"Find your comfort zone. Then leave it.",  
	"Failure is not falling down, but refusing to get up.", 
	"FACT: Thinking about working out burns approximately zero calories per hour.",  
	"Everything you need is already inside.",  
	"Every accomplishment starts with the decision to try.",  
	"Eat clean. Drink water. Stay active. Be healthy.", 
	"Dreams don’t work unless you do.",  
	"Don’t wish for it. Work for it.",  
	"Don’t give up what you want most for what you want now.", 
	"Do not set out to build a wall. Set out to lay one perfect brick each day.",  
	"Do a little more each day than you think you possibly can.",  
	"Devote yourself to an idea. Go make it happen. Struggle on it. Overcome your fears. Smile. Don’t forget – this is your dream.",  
	"Deep inside you there is a person who refuses to be kept deep inside you.",  
	"Comparison is the thief of joy. Do not compare yourself to others.",  
	"Change happens when the pain of staying the same is greater than the pain of change.",  
	"Believe in yourself even when no one else does.",  
	"Being challenged in life is inevitable. Being defeated is optional.",  
	"Be so happy that when others look at you they become happy too.", 
	"Ask yourself if what you’re doing today is getting you closer to where you want to be tomorrow.",  
	"Action always beats intention.",  
	"A goal without a plan is just a wish.",  
	"A change in behavior begins with a change in heart.", 
	"Ability is what you’re capable of doing. Motivation determines what you do. Attitude determines how well you do it.",  
	"Ask your doctor if getting off your ass is right for you.",  
	"Be so good they can’t ignore you.",  
	"Be the change you want to see in the world.",  
	"Being defeated is often a temporary condition … giving up is what makes it permanent.",  
	"Believe you can, and you’re halfway there.",  
	"Change your thoughts and you’ll change your world.",  
	"Decide that you want it more than you are afraid of it.",  
	"Destiny is all about the choices we make and the chances we take.",  
	"Discipline is doing what you know needs to be done, even if you don’t want to do it.",  
	"Do it with passion or not at all. ", 
	"Do something today that your future self will thank you for.",  
	"Don’t be upset by the results you didn’t get with the work you didn’t do.",  
	"Don’t let anyone’s ignorance, hate, drama or negativity stop you from being the best person you can be.",  
	"Dream as if you’ll live forever. Live as if you’ll die tomorrow.",  
	"Each morning we are born again. What we do today is what matters most. ", 
	"Eat like sh*t. Live like sh*t. Feel like sh*t.",  
	"Everyone is an athlete. The only difference is that some of us are in training, and some are not.",  
	"Exercise – I never regret it when I do it, but I always regret it when I don’t.", 
	"Fad diets can change your weight. Working out will change your body.",  
	"Fall seven times, get up eight.",  
	"Fit is not a destination, it is a way of life.",  
	"Goals are more achievable when broken down into smaller tasks.",  
	"Happy people don’t have the best of everything. They make the best of everything they have.",  
	"I am what I am today because of the choices I made yesterday. ", 
	"I don’t work out because I hate my body. I work out because I love it. ", 
	"I would rather be covered in sweat at the gym than covered with clothes at the beach.", 
	"I’m gonna make the rest of my life, the best of my life.",  
	"I’m not losing weight, I’m getting rid of it. I have no intention of finding it again.",  
	"If it doesn’t challenge you, it doesn’t change you.",  
	"If no one thinks you can, then you have to. ", 
	"If you do all the small things right, big things happen.",  
	"If you start now, you’ll start seeing results one day earlier than if you wait until tomorrow. Start today.",  
	"If you want something in your life you’ve never had, you’ll have to do something you’ve never done.", 
	"If your dreams don’t scare you, they’re not big enough.",  
	"In the end we just regret the chances we didn’t take.",  
	"It does not matter how slowly you go, so long as you do not stop.",  
	"It never gets easier, you just get better.",  
	"It’s a lifestyle. Train like there’s no finish line.",  
	"It’s easier to wake up early and work out than it is to look in the mirror each day and not like what you see.",  
	"It’s not that some people have willpower and some don’t. It’s that some people are ready for change and others are not.",  
	"It’s supposed to be hard. If it wasn’t hard, everyone would do it. The hard…is what makes it great.",  
	"Just go. Getting out the door is always the hardest part.",  
	"Know your limitations, and then defy them.",  
	"Life does not put things in front of you that you are unable to handle.",  
	"Life isn’t about finding yourself. Life is about creating yourself.",  
	"Mistakes are proof that you’re trying.",  
	"Never be afraid to fall apart, because it is an opportunity to rebuild yourself the way you wish you had been all along.",  
	"Never regret anything, because at one time it was exactly what you wanted.",  
	"No one is going to tell you to get off your butt and work out. Motivation comes from within. No one wants this more than you.",  
	"One of the greatest pleasures in life is realizing that two weeks ago your body couldn’t do what it just did.",  
	"Our strength grows out of our weaknesses.",  
	"Passion is pushing yourself when no one else is around.",  
	"Running is cheaper than therapy.",  
	"Some quit due to slow progress, never grasping the fact that slow progress…is progress.",  
	"Start by doing what’s necessary. Then do what’s possible. Suddenly you are doing the impossible.",  
	"Stop competing with others, and start competing with yourself.",  
	"Strength doesn’t come from what you can do, it comes from overcoming what you once couldn’t.",  
	"Strong is what happens when you run out of weak.",  
	"Success is the sum of small efforts repeated day in and day out.",  
	"Take care of your body, and your body will take care of you.",  
	"Take your weight loss one pound at a time.",  
	"The #1 reason people give up is because they tend to look at how far they still have to go, instead of how far they’ve gotten.",  
	"The difference between “try” and “triumph” is just a little umph!",
	"The difference between your body this week and next week is what you do for the next 7 days to achieve your goals.",  
	"The food you eat can be either the safest and most powerful form of medicine or the slowest form of poison.",  
	"The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.",  
	"The happiest people do not have the best of everything. They make the best of everything they have.",  
	"The most important weight loss muscle? Your brain. Change your mind and change your body.",  
	"The question isn’t can you, it’s will you?",
	"The tragedy of life is not death, but what we let die inside of us while we live.",  
	"There are plenty of obstacles in your path. Don’t allow yourself to become one of them.",  
	"There are 1,440 minutes in a day. Use 30 of them to work out.",  
	"Think about how far you have gotten, and not about how far you still have to go.",  
	"Those who try to do something and fail are infinitely better than those who try to do nothing and succeed.", 
	"Today is another chance. Make yourself proud.",  
	"Turn a setback into a comeback.",
	"We do not stop exercising because we grow old – we grow old because we stop exercising.",  
	"What is the point of being alive if you don’t at least try to do something remarkable?",  
	"When your legs get tired, run with your heart.", 
	"Willpower is a muscle. The more you use it, the stronger it gets.",  
	"You are so much stronger than you think.",  
	"You can have results or excuses – not both.",  
	"You don’t always get what you wish for, you get what you work for.",  
	"You don’t have to see the whole staircase. Just take the first step.",  
	"You have brains in your head. You have feet in your shoes. You can steer yourself in any direction you choose.", 
	"You have to fight through some bad days to earn the best days of your life."
	"You were strong enough to get this far. You are strong enough to keep going."  
	"You won’t get very far if you only work out on the days you feel good.",  
	"You’ve got what it takes, but it will take everything you’ve got.",  
	"Your body can do anything. It’s just your brain you have to convince.",  
	"Your body keeps an accurate journal regardless of what you write down.", 
	"Your mind will quit a thousand times before your body will. Feel the fear and do it anyway!", 
	"Everyone always says follow your dream and your passion but nobody does it.",
	"I know only this for sure: Every run is a new adventure, and every mile is a gift.",
	"Running is a simple activity. Just lace up your shoes and go, one step at a time, like each breath.",
	"Sport, like all life, is about taking your chances.",
	"There are no strangers at the starting line. Just fellow runners who haven't met yet.",
	"I always thought of running just as dancing forward.",
	"Only those who will risk going too far can possibly find out how far they can go.",
	"Don’t bother just to be better than your contemporaries or predecessors. Try to be better than yourself.",
	"Don’t judge your running by your speed.",
	"Leave your watch on the kitchen table and go-freely, like a child.",
	"Consistency requires discipline. Force yourself out the door.",
	"We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses.",
	"If we wait until we’re ready, we'll be waiting the rest of our lives.",
	"At first glance it may appear too hard. Look again. Always look again.",
	"Of all the paths you take in life, make sure a few of them are dirt.",
	"The terrain of my life is constantly shifting. I can either quit of get on my toes.",
	"Be fearless in the pursuit of what sets your soul on fire.",
	"Don’t listen to your inner fatty, she's an evil witch! She misses cupcakes.",
	"Roses are red. Violets are blue. Go to the gym.",
	"Exercise in the morning before your brain figures out what you're doing.",
	"Suck it up now so you don't have to such it in later.",
	"Hustle for that muscle.",
	"When life knocks you down… do a burpee!",
	"If you're waiting for a sign… HERE IT IS. GO WORK OUT.",
	"Rise up. Start fresh. See the bright opportunity in each new day.",
	"Be a badass with a good ass.",
	"Tired of my fitness quotes? Just block everything health and fitness related. You know, like in your real life.",
	"Train like a beast. Look like a beauty.",
	"A one hour workout is 4% of your day. No excuses.",
]